name: Hello World Workflow

# Trigger the workflow on push to any branch
on: 
  push:
    branches:
      - "*"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Print "Hello World"
      - name: Say Hello
        run: echo "Hello World!"
